server:
  port: 1121
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bych_qhjk?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
#mybatis config
mybatis:
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  offsetAsPageNum: true
  reasonable: true
  support-methods-arguments: true
  page-size-zero: true
logging:
  config: classpath:logback-dev.xml