package club.map.base.model;

import club.map.core.model.RootObject;
import club.map.core.model.TableName;

@TableName("business_log")
public class BusinessLog extends RootObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_log.log_type
     *
     * @mbggenerated Wed Aug 03 18:11:10 GMT+08:00 2016
     */
    private Integer logType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_log.log_key
     *
     * @mbggenerated Wed Aug 03 18:11:10 GMT+08:00 2016
     */
    private String logKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_log.log_value
     *
     * @mbggenerated Wed Aug 03 18:11:10 GMT+08:00 2016
     */
    private String logValue;

    private String logRes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_log.log_type
     *
     * @return the value of business_log.log_type
     *
     * @mbggenerated Wed Aug 03 18:11:10 GMT+08:00 2016
     */
    public Integer getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_log.log_type
     *
     * @param logType the value for business_log.log_type
     *
     * @mbggenerated Wed Aug 03 18:11:10 GMT+08:00 2016
     */
    public void setLogType(Integer logType) {
        this.logType = logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_log.log_key
     *
     * @return the value of business_log.log_key
     *
     * @mbggenerated Wed Aug 03 18:11:10 GMT+08:00 2016
     */
    public String getLogKey() {
        return logKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_log.log_key
     *
     * @param logKey the value for business_log.log_key
     *
     * @mbggenerated Wed Aug 03 18:11:10 GMT+08:00 2016
     */
    public void setLogKey(String logKey) {
        this.logKey = logKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_log.log_value
     *
     * @return the value of business_log.log_value
     *
     * @mbggenerated Wed Aug 03 18:11:10 GMT+08:00 2016
     */
    public String getLogValue() {
        return logValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_log.log_value
     *
     * @param logValue the value for business_log.log_value
     *
     * @mbggenerated Wed Aug 03 18:11:10 GMT+08:00 2016
     */
    public void setLogValue(String logValue) {
        this.logValue = logValue;
    }

    public String getLogRes() {
        return logRes;
    }

    public void setLogRes(String logRes) {
        this.logRes = logRes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_log
     *
     * @mbggenerated Wed Aug 03 18:11:10 GMT+08:00 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", logType=").append(logType);
        sb.append(", logKey=").append(logKey);
        sb.append(", logValue=").append(logValue);
        sb.append("]");
        return sb.toString();
    }
}